View/Controllers/BusController.cs
using Core.Models;
using Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace View.Controllers;
[Authorize(Policy = "ManagerOnly")]
public class BusController : Controller
{
    private readonly IBusRepository _busRepository;
    private readonly ILogger<BusController> _logger;

    public BusController(IBusRepository busRepository, ILogger<BusController> logger)
    {
        _busRepository = busRepository;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var buses = await _busRepository.Get();
        return View(buses);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Bus model)
    {
        if (ModelState.IsValid)
        {
            await _busRepository.Add(model);
            _logger.LogInformation("Created new bus with ID {id}, Bus Number {number} at {time}.", model.Id, model.BusNumber, DateTime.Now);
            return RedirectToAction("Index");
        }
        _logger.LogError("Failed bus creation validation at {time}.", DateTime.Now);
        return View(model);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var model = await _busRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Bus to update not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Bus model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _busRepository.Update(model);
                _logger.LogInformation("Updated bus with ID {id} at {time}.", model.Id, DateTime.Now);
            } catch
            {
                _logger.LogError("Updating bus with ID {id} failed at {time}.", model.Id, DateTime.Now);
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        return View(model);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var model = await _busRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Bus to delete not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        try
        {
            await _busRepository.Delete(id);
            _logger.LogInformation("Deleted bus with ID {id} at {time}.", id, DateTime.Now);
        }
        catch
        {
            _logger.LogError("Deleting bus with ID {id} failed at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return RedirectToAction("Index");
    }
}

View/Controllers/LoopController.cs
using Core.Models;
using Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using View.Models;

namespace View.Controllers;
[Authorize(Policy = "ManagerOnly")]
public class LoopController : Controller
{
    private readonly ILoopRepository _loopRepository;
    private readonly IStopRepository _stopRepository;
    private readonly IEntryRepository _entryRepository;
    private readonly ILogger<LoopController> _logger;

    public LoopController(ILoopRepository loopRepository, IStopRepository stopRepository, IEntryRepository entryRepository, ILogger<LoopController> logger)
    {
        _loopRepository = loopRepository;
        _stopRepository = stopRepository;
        _entryRepository = entryRepository;
        _logger = logger;
    }

    public async Task<IActionResult> Index(string loopId, string filterByVisits)
    {
        var stops = await _stopRepository.Get();
        var loops = await _loopRepository.Get();
        var entries = await _entryRepository.Get();
        var stopsForMap = new List<Stop>();

        var loopIds = loops.Select(l => l.Id);
        
        List<SelectListItem> loopSelectList = new SelectList(loops, "Id", "Name").ToList();
        loopSelectList.Insert(0, new SelectListItem
        {
            Text = "",
            Value = "",
            Selected = true
        });
        ViewBag.AvailableLoops = loopSelectList;

        stopsForMap = stops;

        if (!string.IsNullOrEmpty(loopId) && loopIds.Contains(int.Parse(loopId)))
        {
            var loopToFilterTo = loops.Where(l => l.Id == int.Parse(loopId)).First();

            stopsForMap = loopToFilterTo.Routes.Select(r => r.Stop).ToList();

            loopSelectList.Where(l => l.Value == loopId).First().Selected = true;
        }

        if (!string.IsNullOrEmpty(filterByVisits))
        {
            if(entries.Count < 1)
            {
                stopsForMap = new List<Stop>();
            } else
            {
                var stopsWithManyPeople = entries.OrderByDescending(e => e.Boarded).Select(e => e.Stop).Take(5).ToList();
                stopsForMap = stopsWithManyPeople.Join(stopsForMap, s => s.Id, s2 => s2.Id, (s, s2) => s).ToList();
            }

        }

        ViewBag.StopsForMap = stopsForMap;

        return View(loops);
    }

    public IActionResult Create()
    {
        return View(new LoopViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Create(LoopViewModel model)
    {
        if (ModelState.IsValid)
        {
            var loop = new Loop
            {
                Name = model.Name
            };
            await _loopRepository.Add(loop);
            _logger.LogInformation("Created new loop with ID {id}, Name {name} at {time}.", model.Id, model.Name, DateTime.Now);
            return RedirectToAction("Index");
        }
        _logger.LogError("Failed loop creation validation at {time}.", DateTime.Now);
        return View(model);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var model = await _loopRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Loop to update not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        var viewModel = new LoopViewModel
        {
            Id = model.Id,
            Name = model.Name,
        };

        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(LoopViewModel model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                var loop = new Loop
                {
                    Id = model.Id,
                    Name = model.Name
                };
                await _loopRepository.Update(loop);
                _logger.LogInformation("Updated loop with ID {id} at {time}.", model.Id, DateTime.Now);
            }
            catch
            {
                _logger.LogError("Updating loop with ID {id} failed at {time}.", model.Id, DateTime.Now);
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        return View(model);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var model = await _loopRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Loop to delete not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        try
        {
            await _loopRepository.Delete(id);
            _logger.LogInformation("Deleted bus with ID {id} at {time}.", id, DateTime.Now);
        }
        catch
        {
            _logger.LogError("Deleting bus with ID {id} failed at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return RedirectToAction("Index");
    }
}

View/Controllers/RouteController.cs
using Core.Models;
using Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using View.Models;

namespace View.Controllers;
[Authorize(Policy = "ManagerOnly")]
public class RouteController : Controller
{
    private readonly IRouteRepository _routeRepository;
    private readonly IStopRepository _stopRepository;
    private readonly ILoopRepository _loopRepository;
    private readonly ILogger<RouteController> _logger;

    public RouteController(IRouteRepository routeRepository, IStopRepository stopRepository, ILoopRepository loopRepository, ILogger<RouteController> logger)
    {
        _routeRepository = routeRepository;
        _stopRepository = stopRepository;
        _loopRepository = loopRepository;
        _logger = logger;
    }

    private async Task<List<SelectListItem>> GetAvailableStops()
    {
        var stops = await _stopRepository.Get();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var stop in stops)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = stop.Name,
                Value = stop.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    private async Task<List<SelectListItem>> GetAvailableLoops()
    {
        var loops = await _loopRepository.Get();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var loop in loops)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = loop.Name,
                Value = loop.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    public async Task<IActionResult> Index(string loopId)
    {
        var loops = await GetAvailableLoops();
        var loopIds = loops.Select(l => l.Value);
        ViewBag.AvailableLoops = loops;
            
        var routes = await _routeRepository.Get();
        if (!loopIds.Contains(loopId))
        {
            var defaultId = "0";
            if(loopIds.Any())
            {
                defaultId = loopIds.ToList().First();
            }
            
            return View(routes.Where(r => r.LoopId == int.Parse(defaultId)).OrderBy(r => r.Order));
        }
        loops.Where(l => l.Value == loopId).First().Selected = true;
        ViewBag.AvailableLoops = loops;
        return View(routes.Where(r => r.LoopId == int.Parse(loopId)).OrderBy(r => r.Order));
    }

    public async Task<IActionResult> Create()
    {
        ViewBag.AvailableStops = await GetAvailableStops();
        ViewBag.AvailableLoops = await GetAvailableLoops();

        return View(new RouteViewModel());
    }

    [HttpPost]
    public async Task<IActionResult> Create(RouteViewModel model)
    {
        if (ModelState.IsValid)
        {
            var routeCount = (await _loopRepository.Get(model.LoopId)).Routes.Count;
            var route = new Core.Models.Route
            {
                Order = routeCount + 1,
                StopId = model.StopId,
                LoopId = model.LoopId
            };
            await _routeRepository.Add(route);
            _logger.LogInformation("Created new route with ID {id}, Order {order}, Stop {stop} at {time}.", model.Id, routeCount + 1, model.StopId, DateTime.Now);
            return RedirectToAction("Index");
        }
        _logger.LogError("Failed route validation at {time}.", DateTime.Now);
        return View(model);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var model = await _routeRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Route to update not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        ViewBag.AvailableStops = await GetAvailableStops();

        var viewModel = new RouteEditViewModel
        {
            Id = model.Id,
            Order = model.Order,
            StopId = model.StopId,
            LoopId = model.LoopId
        };


        return View(viewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(RouteEditViewModel model)
    {
        if (ModelState.IsValid)
        {
            var route = new Core.Models.Route
            {
                Id = model.Id,
                Order = model.Order,
                StopId = model.StopId,
                LoopId = model.LoopId
            };
            try
            {
                await _routeRepository.Update(route);
                _logger.LogInformation("Updated route with ID {id} at {time}.", model.Id, DateTime.Now);
            }
            catch
            {
                _logger.LogError("Updating route with ID {id} failed at {time}.", model.Id, DateTime.Now);
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        return View(model);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var model = await _routeRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Route to delete not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        try
        {
            await _routeRepository.Delete(id);
            _logger.LogInformation("Deleted route with ID {id} at {time}.", id, DateTime.Now);
        }
        catch
        {
            _logger.LogError("Deleting route with ID {id} failed at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return RedirectToAction("Index");
    }

    [HttpPost, ActionName("SwapOrders")]
    public async Task<IActionResult> SwapOrders(int currentId, int updatedId)
    {
        await _routeRepository.SwapOrders(currentId, updatedId);
        _logger.LogInformation("Routes {id} and {anotherid} swapped order at {time}.", currentId, updatedId, DateTime.Now);
        return Ok();
    }
}

View/Controllers/StopController.cs
using Core.Models;
using Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace View.Controllers;
[Authorize(Policy = "ManagerOnly")]
public class StopController : Controller
{
    private readonly IStopRepository _stopRepository;
    private readonly ILogger<StopController> _logger;

    public StopController(IStopRepository stopRepository, ILogger<StopController> logger)
    {
        _stopRepository = stopRepository;
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        var stops = await _stopRepository.Get();
        return View(stops);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Stop model)
    {
        if (ModelState.IsValid)
        {
            await _stopRepository.Add(model);
            _logger.LogInformation("Created new stop with ID {id}, Name {name} at {time}.", model.Id, model.Name, DateTime.Now);
            return RedirectToAction("Index");
        }
        _logger.LogError("Failed stop creation validation at {time}.", DateTime.Now);
        return View(model);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var model = await _stopRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Stop to update not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Stop model)
    {
        if (ModelState.IsValid)
        {
            try
            {
                await _stopRepository.Update(model);
                _logger.LogInformation("Updated stop with ID {id} at {time}.", model.Id, DateTime.Now);
            }
            catch
            {
                _logger.LogError("Updating stop with ID {id} failed at {time}.", model.Id, DateTime.Now);
                return NotFound();
            }
            return RedirectToAction("Index");
        }

        return View(model);
    }

    public async Task<IActionResult> Delete(int id)
    {
        var model = await _stopRepository.Get(id);

        if (model == null)
        {
            _logger.LogWarning("Stop to delete not found with ID {id} at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return View(model);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeletePost(int id)
    {
        try
        {
            _logger.LogInformation("Deleted stop with ID {id} at {time}.", id, DateTime.Now);
            await _stopRepository.Delete(id);
        }
        catch
        {
            _logger.LogError("Deleting stop with ID {id} failed at {time}.", id, DateTime.Now);
            return NotFound();
        }

        return RedirectToAction("Index");
    }
}

View/Views/Shared/_Layout.cshtml
@using Core.Models;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Driver> SignInManager
@inject UserManager<Driver> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - View</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/View.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    @if (ViewBag.IsLoginPage != true)
    {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                var isManager = bool.Parse(User.FindFirst("IsManager")?.Value ?? "false");
                                var isActivated = bool.Parse(User.FindFirst("IsActivated")?.Value ?? "false");
                                if (isManager)
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Bus" asp-action="Index">Bus</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">Driver</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Loop" asp-action="Index">Loop</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Route" asp-action="Index">Route</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Stop" asp-action="Index">Stop</a>
                                    </li>
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Entry" asp-action="Index">Entry</a>
                                    </li>
                                }
                                if (isActivated && !isManager)
                                {
                                    <li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Entry" asp-action="StartDriving">Start Driving</a>
                                    </li>
                                }
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Log Out</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Log In</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    }
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>