View/Models/EntryViewModel.cs
using Core.Models;

namespace View.Models
{
    public class EntryViewModel
    {
        public int BusId { get; set; }
        public int LoopId { get; set; }
        public int StopId { get; set; }
        public int Boarded { get; set; }
        public int LeftBehind { get; set; }
    }
}

View/Controllers/EntryController.cs
using Core.Models;
using Core.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Security.Claims;
using View.Models;

namespace View.Controllers;
[Authorize]
public class EntryController : Controller
{
    private readonly IEntryRepository _entryRepository;
    private readonly IStopRepository _stopRepository;
    private readonly IBusRepository _busRepository;
    private readonly ILoopRepository _loopRepository;
    private readonly ILogger<EntryController> _logger;
    private readonly UserManager<Driver> _userManager;

    public EntryController(IEntryRepository entryRepository, IStopRepository stopRepository, UserManager<Driver> userManager, IBusRepository busRepository, ILoopRepository loopRepository, ILogger<EntryController> logger)
    {
        _entryRepository = entryRepository;
        _stopRepository = stopRepository;
        _userManager = userManager;
        _busRepository = busRepository;
        _loopRepository = loopRepository;
        _logger = logger;
    }

    private async Task<List<SelectListItem>> GetAvailableBusses()
    {
        var busses = await _busRepository.Get();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var bus in busses)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = bus.BusNumber.ToString(),
                Value = bus.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    private async Task<List<SelectListItem>> GetAvailableLoops()
    {
        var loops = await _loopRepository.Get();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var loop in loops)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = loop.Name,
                Value = loop.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    private async Task<List<SelectListItem>> GetAvailableStops(int loopId)
    {
        var loop = await _loopRepository.Get(loopId);
        var viewbagSelect = new List<SelectListItem>();
        foreach (var route in loop.Routes)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = route.Stop.Name,
                Value = route.Stop.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    private async Task<List<SelectListItem>> GetAvailableStops()
    {
        var stops = await _stopRepository.Get();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var stop in stops)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = stop.Name,
                Value = stop.Id.ToString()
            });
        }
        return viewbagSelect;
    }

    private async Task<List<SelectListItem>> GetAvailableDrivers()
    {
        var drivers = _userManager.Users.ToList();
        var viewbagSelect = new List<SelectListItem>();
        foreach (var driver in drivers)
        {
            viewbagSelect.Add(new SelectListItem
            {
                Text = driver.FirstName + " " + driver.LastName,
                Value = driver.Id
            });
        }
        return viewbagSelect;
    }
    [Authorize(Policy = "ManagerOnly")]
    public async Task<IActionResult> Index(string loopId, string busId, string stopId, string driverId, string day)
    {
        var loops = await GetAvailableLoops();
        loops.Insert(0, new SelectListItem
        {
            Text = "",
            Value = ""
        });
        ViewBag.AvailableLoops = loops;

        var busses = await GetAvailableBusses();
        busses.Insert(0, new SelectListItem
        {
            Text = "",
            Value = ""
        });
        ViewBag.AvailableBusses = busses;

        var stops = await GetAvailableStops();
        stops.Insert(0, new SelectListItem
        {
            Text = "",
            Value = ""
        });
        ViewBag.AvailableStops = stops;

        var drivers = await GetAvailableDrivers();
        drivers.Insert(0, new SelectListItem
        {
            Text = "",
            Value = ""
        });
        ViewBag.AvailableDrivers = drivers;

        var entries = await _entryRepository.Get();

        if (!string.IsNullOrEmpty(loopId))
        {
            entries = entries.Where(e => e.LoopId == int.Parse(loopId)).ToList();
        }

        if (!string.IsNullOrEmpty(busId))
        {
            entries = entries.Where(e => e.BusId == int.Parse(busId)).ToList();
        }

        if (!string.IsNullOrEmpty(stopId))
        {
            entries = entries.Where(e => e.StopId == int.Parse(stopId)).ToList();
        }

        if (!string.IsNullOrEmpty(driverId))
        {
            entries = entries.Where(e => e.DriverId == driverId).ToList();
        }

        if (!string.IsNullOrEmpty(day))
        {
            entries = entries.Where(e => e.Timestamp.Date.Equals(DateTime.Parse(day).Date)).ToList();
        }


        return View(entries);
    }

    [Authorize(Policy = "ActivatedOnly")]
    public async Task<IActionResult> StartDriving()
    {
        ViewBag.AvailableBusses = await GetAvailableBusses();
        ViewBag.AvailableLoops = await GetAvailableLoops();

        return View(new EntryStartViewModel());
    }

    [HttpPost]
    [Authorize(Policy = "ActivatedOnly")]
    public async Task<IActionResult> StartDriving(EntryStartViewModel model)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction("Create", new {busId = model.BusId, loopId = model.LoopId});
        }
        _logger.LogError("Failed entry start validation at {time}.", DateTime.Now);
        return View(model);
    }

    [Authorize(Policy = "ActivatedOnly")]
    public async Task<IActionResult> Create(int busId, int loopId)
    {
        ViewBag.AvailableStops = await GetAvailableStops(loopId);

        return View(new EntryViewModel
        {
            BusId = busId,
            LoopId = loopId
        });
    }

    [HttpPost]
    [Authorize(Policy = "ActivatedOnly")]
    public async Task<IActionResult> Create(EntryViewModel model)
    {
        if (ModelState.IsValid)
        {
            var userId = _userManager.GetUserId(User);
            var routeId = (await _loopRepository.Get(model.LoopId)).Routes.Where(r => r.StopId == model.StopId).First().Id;
            var entry = new Entry
            {
                DriverId = userId,
                BusId = model.BusId,
                LoopId = model.LoopId,
                StopId = model.StopId,
                RouteId = routeId,
                Boarded = model.Boarded,
                LeftBehind = model.LeftBehind,
                Timestamp = DateTime.Now
            };
            try
            {
                await _entryRepository.Add(entry);
                _logger.LogInformation("Entry created by {driver} on loop {loop} for stop {stop} on bus {bus} at {time}.", entry.DriverId, entry.LoopId, entry.StopId, entry.BusId, DateTime.Now);
            }
            catch
            {
                _logger.LogError("Entry failed created by {driver} on loop {loop} for stop {stop} on bus {bus} at {time}.", entry.DriverId, entry.LoopId, entry.StopId, entry.BusId, DateTime.Now);
                return NotFound();
            }
            return Ok();
        }
        _logger.LogError("Failed entry create validation at {time}.", DateTime.Now);
        return View(model);
    }

    [Authorize(Policy = "ManagerOnly")]
    public async Task<IActionResult> Add()
    {
        ViewBag.AvailableLoops = await GetAvailableLoops();
        ViewBag.AvailableBusses = await GetAvailableBusses();
        ViewBag.AvailableStops = await GetAvailableStops();
        ViewBag.AvailableDrivers= await GetAvailableDrivers();

        var viewModel = new EntryAddViewModel
        {
        };


        return View(viewModel);
    }

    [HttpPost]
    [Authorize(Policy = "ManagerOnly")]
    public async Task<IActionResult> Add(EntryAddViewModel model)
    {
        if (ModelState.IsValid)
        {
            int routeId;
            try
            {
                routeId = (await _loopRepository.Get(model.LoopId)).Routes.Where(r => r.StopId == model.StopId).First().Id;
            } catch
            {
                ModelState.AddModelError(string.Empty, "The stop selected must be part of the loop.");
                ViewBag.AvailableLoops = await GetAvailableLoops();
                ViewBag.AvailableBusses = await GetAvailableBusses();
                ViewBag.AvailableStops = await GetAvailableStops();
                ViewBag.AvailableDrivers = await GetAvailableDrivers();
                return View(model);
            }
            var entry = new Entry
            {
                DriverId = model.DriverId,
                Boarded = model.Boarded,
                LeftBehind = model.LeftBehind,
                BusId = model.BusId,
                StopId = model.StopId,
                LoopId = model.LoopId,
                RouteId = routeId,
                Timestamp = model.Date.ToDateTime(model.Time),
            };
            try
            {
                await _entryRepository.Add(entry);
                _logger.LogInformation("Entry created for loop {loop} for stop {stop} on bus {bus} at {time}.", entry.LoopId, entry.StopId, entry.BusId, DateTime.Now);
            }
            catch
            {

View/Views/Entry/Add.cshtml
@model View.Models.EntryAddViewModel

@{
    ViewData["Title"] = "Add";
}

<h1>Add Entry</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BusId" class="control-label">Bus</label>
                <select asp-for="BusId" class="form-control" asp-items="ViewBag.AvailableBusses"></select>
            </div>
            <div class="form-group">
                <label asp-for="LoopId" class="control-label">Loop</label>
                <select asp-for="LoopId" class="form-control" asp-items="ViewBag.AvailableLoops"></select>
            </div>
            <div class="form-group">
                <label asp-for="StopId" class="control-label">Stop</label>
                <select asp-for="StopId" class="form-control" asp-items="ViewBag.AvailableStops"></select>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label">Driver</label>
                <select asp-for="DriverId" class="form-control" asp-items="ViewBag.AvailableDrivers"></select>
            </div>
            <div class="form-group">
                <label asp-for="Boarded" class="control-label"></label>
                <input asp-for="Boarded" class="form-control" />
                <span asp-validation-for="Boarded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeftBehind" class="control-label">Left Behind</label>
                <input asp-for="LeftBehind" class="form-control" />
                <span asp-validation-for="LeftBehind" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label">Time</label>
                <input type="time" asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label">Date</label>
                <input type="date" asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

View/Views/Entry/Create.cshtml
@model View.Models.EntryViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Entries</h1>
<hr />
<div class="row">
    @if (ViewBag.AvailableStops.Count < 1)
    {
        <p>You must have at least one Stop created to start driving.</p>
    }
    else
    {
        <div style="font-size: 1.5rem" class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="successModalCenterTitle">Entry Added</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p id="modal-text"></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 mx-auto" style="font-size: 2rem;width: 100%;">
            <form asp-action="StartDriving" style="width: 100%;">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="LoopId" />
                <input type="hidden" asp-for="BusId" />
                <div class="form-group">
                    <label asp-for="StopId" class="control-label">Stop</label>
                    <select id="stops" asp-for="StopId" class="form-select form-select-lg" asp-items="ViewBag.AvailableStops" style="font-size: 2rem;"></select>
                </div>
                <div class="form-group">
                    <div class="d-flex p-2" style="gap: 20px; align-items: center; text-align: center;">
                        <button type="button" data-change="boarded" class="dec btn btn-lg btn-primary">-</button>
                        <label asp-for="Boarded" class="control-label"></label>
                        <input id="boarded" asp-for="Boarded" class="form-control input-lg" style="font-size: 2rem;" />
                        <span asp-validation-for="Boarded" class="text-danger"></span>
                        <button type="button" data-change="boarded" class="inc btn btn-lg btn-primary">+</button>
                    </div>
                    
                </div>
                <div class="form-group">
                    <div class="d-flex p-2" style="gap: 20px; align-items: center; text-align: center;">
                        <button type="button" data-change="leftbehind" class="dec btn btn-lg btn-primary">-</button>
                        <label asp-for="LeftBehind" class="control-label input-lg">Left Behind</label>
                        <input id="leftbehind" asp-for="LeftBehind" class="form-control input-lg" style="font-size: 2rem;" />
                        <span asp-validation-for="LeftBehind" class="text-danger"></span>
                        <button type="button" data-change="leftbehind" class="inc btn btn-lg btn-primary">+</button>
                    </div>
                </div>
                <div class="form-group text-center" style="margin-top: 20px">
                    <input type="submit" value="Submit" class="btn btn-lg btn-primary" />
                </div>
            </form>
        </div>
    }
</div>
<div class="mx-auto text-center" style="margin-top: 20px">
    <a class="btn btn-lg btn-secondary" asp-controller="Home" asp-action="Index">Finish Driving</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            $(".inc").click(function () {
                let valueToChange = $(this).data("change");
                let inputToChange = $("#" + valueToChange);
                let value = parseInt(inputToChange.val());
                inputToChange.val(value + 1)
            });

            $(".dec").click(function () {
                let valueToChange = $(this).data("change");
                let inputToChange = $("#" + valueToChange);
                let value = parseInt(inputToChange.val());
                inputToChange.val(value - 1)
            });

            $("form").submit(function (event) {
                event.preventDefault();
                $.post("/Entry/Create", $(this).serialize(), function () {
                    let stops = $("#stops");
                    let successModal = $('#successModal');

                    successModal.on('show.bs.modal', function (event) {
                        let selectedOptionText = stops.find("option:selected").text();
                        let modal = $(this)
                        modal.find('.modal-body p').text("Successfully added an entry for " + selectedOptionText + ".");
                    })
                    successModal.modal('show')

                    let currentIndex = stops.prop("selectedIndex");
                    let numOptions = $("select option").length;
                    let nextIndex = (currentIndex + 1) % numOptions;
                    stops.prop("selectedIndex", nextIndex);
                    $("#boarded").val(0);
                    $("#leftbehind").val(0);

                    setTimeout(function () {
                        successModal.modal('hide')
                    }, 3000);
                })
                .fail(function (response) {
                    console.error("Error while submitting entry:", response);
                });
            });
        });
    </script>
}

View/Views/Entry/Delete.cshtml
@model Core.Models.Entry

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Entry</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entry</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Time
        </dt>
        <dd class = "col-sm-10">
            @Html.Raw(ViewBag.Time)
        </dd>
        <dt class="col-sm-2">
            Stop
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Stop.Name)
        </dd>
        <dt class="col-sm-2">
            Loop
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Loop.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

View/Views/Entry/Edit.cshtml
@model View.Models.EntryEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Entry</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="BusId" class="control-label">Bus</label>
                <select asp-for="BusId" class="form-control" asp-items="ViewBag.AvailableBusses"></select>
            </div>
            <div class="form-group">
                <label asp-for="LoopId" class="control-label">Loop</label>
                <select asp-for="LoopId" class="form-control" asp-items="ViewBag.AvailableLoops"></select>
            </div>
            <div class="form-group">
                <label asp-for="StopId" class="control-label">Stop</label>
                <select id="stops" asp-for="StopId" class="form-control" asp-items="ViewBag.AvailableStops"></select>
            </div>
            <div class="form-group">
                <label asp-for="Boarded" class="control-label"></label>
                <input asp-for="Boarded" class="form-control" />
                <span asp-validation-for="Boarded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeftBehind" class="control-label">Left Behind</label>
                <input asp-for="LeftBehind" class="form-control" />
                <span asp-validation-for="LeftBehind" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label">Time</label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label">Date</label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

View/Views/Entry/Index.cshtml
@model IEnumerable<Core.Models.Entry>

@{
    ViewData["Title"] = "Index";
}

<h1>Entries</h1>
<p>
    <a asp-action="Add">Create New</a>
</p>
<h4>Filter By:</h4>
@using (Html.BeginForm("Index", "Entry", FormMethod.Get))
{
    <div class="form-group">
        <label for="LoopId" class="control-label">Loop:</label>
        <select id="LoopId" name="LoopId" class="form-control" asp-items="ViewBag.AvailableLoops"></select>
    </div>

    <div class="form-group">
        <label for="BusId" class="control-label">Bus:</label>
        <select id="BusId" name="BusId" class="form-control" asp-items="ViewBag.AvailableBusses"></select>
    </div>

    <div class="form-group">
        <label for="DriverId" class="control-label">Driver:</label>
        <select id="DriverId" name="DriverId" class="form-control" asp-items="ViewBag.AvailableDrivers"></select>
    </div>

    <div class="form-group">
        <label for="StopId" class="control-label">Stop:</label>
        <select id="StopId" name="StopId" class="form-control" asp-items="ViewBag.AvailableStops"></select>
    </div>

    <div class="form-group">
        <label for="Day" class="control-label">Day:</label>
        <input type="date" id="Day" name="Day" class="form-control" />
    </div>

    <div class="form-group d-flex p-2" style="margin-top: 20px; gap: 20px;">
        <button class="btn btn-primary" onclick="this.form.submit()">Filter</button>
        <button type="button" class="btn btn-primary" id="export">Export</button>
    </div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Boarded)
            </th>
            <th>
                Left Behind
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Stop)
            </th>
            <th>
                Time
            </th>
            <th>
                Date
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Loop)
            </th>
            <th>
                Driver
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bus)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Boarded)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LeftBehind)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Stop.Name)
                </td>
                <td>
                    @Html.Raw(item.Timestamp.ToString("HH:mm"))
                </td>
                <td>
                    @Html.Raw(item.Timestamp.ToString("d"))
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Loop.Name)
                </td>
                <td>
                    @Html.Raw(item.Driver.FirstName + " " + item.Driver.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bus.BusNumber)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(document).ready(function () {
            function tableToCSV() {
                let csv_data = [];

                var rows = document.getElementsByTagName('tr');
                for (let i = 0; i < rows.length; i++) {
                    let cols = rows[i].querySelectorAll('td,th');

                    let csvrow = [];
                    for (let j = 0; j < cols.length - 1; j++) {
                        csvrow.push(cols[j].textContent.trim());
                    }
                    let rowData = csvrow.join(",");
                    csv_data.push(rowData);
                }
                console.log(csv_data)
                csv_data = csv_data.join('\n');
                downloadCSVFile(csv_data);
            }

            function downloadCSVFile(csv_data) {
                CSVFile = new Blob([csv_data], { type: "text/csv" });

                let temp_link = document.createElement('a');

                temp_link.download = "Entries.csv";
                let url = window.URL.createObjectURL(CSVFile);
                temp_link.href = url;

                temp_link.style.display = "none";
                document.body.appendChild(temp_link);

                temp_link.click();
                document.body.removeChild(temp_link);
            }

            $("#export").click(function () {
                tableToCSV();
            });
        });
    </script>
    }

View/Views/Entry/StartDriving.cshtml
@model View.Models.EntryStartViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Start Driving</h1>
<hr />
<div class="row">
    @if (ViewBag.AvailableLoops.Count < 1 || ViewBag.AvailableBusses.Count < 1)
    {
        <p>You must have at least one Loop and Bus created to start driving.</p>
    }
    else
    {
        <div class="col-md-4 mx-auto" style="font-size: 2rem">
            <form asp-action="StartDriving">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="BusId" class="control-label">Bus</label>
                    <select asp-for="BusId" class="form-control" asp-items="ViewBag.AvailableBusses"></select>
                </div>
                <div class="form-group">
                    <label asp-for="LoopId" class="control-label">Loop</label>
                    <select asp-for="LoopId" class="form-control" asp-items="ViewBag.AvailableLoops"></select>
                </div>
                <div class="form-group" style="margin-top: 20px">
                    <input type="submit" value="Start" class="btn btn-lg btn-primary" />
                </div>
            </form>
        </div>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}